**Data types for ndarrays**

In [1]:
import numpy as np
arr1=np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('int32')

**ndarray data type casting**

In [2]:
arr1.dtype

dtype('int32')

In [3]:
arr2=arr1.astype(np.float64)
arr2

array([1., 2., 3.])

In [4]:
arr2.dtype

dtype('float64')

**"asarry" creates new array**

In [5]:
data2=[[1,2,3,4],[5,6,7,8]]
arr3=np.array(data2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr3.astype(arr2.dtype)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])